---
- name: Determine if RHEL7
  shell: "grep 'Red Hat Enterprise Linux.*release 7' /etc/redhat-release"
  register: is_rhel7
  failed_when: false
  changed_when: false
- debug: var=is_rhel7

- include: rhel.yml
  when: is_rhel7.rc == 0

- include: ubuntu.yml
  when: is_rhel7.rc != 0
